spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        username: sa
        password: 
        driverClassName: org.h2.Driver
        
security:
    oauth2:
        resource:
            filter-order: 3        

